version: 2.1
jobs:
  build:
    steps:
      - run: echo "this is the build job"
  test:
    steps:
      - run: echo "this is the test job"

workflows:
  build:
    jobs:
      - node/build
  test:
    jobs:
      - node/test
